/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  mySidebar: [
  	'intro',
  	{
  	  type: 'category',
  	  label: '树莓派开发 - Raspi',
  	  items: ['树莓派开发 - Raspi/openwrt','树莓派开发 - Raspi/test1'],
  	},
    {
      type: 'category',
      label: '开发效率UP！',
      items: ['开发效率UP！/coding','开发效率UP！/CLion-STM32'],
    },
    // {
    //   type: 'category',
    //   label: '秘密基地',
    //   items: ['秘密基地/myLove'],
    // },
  	],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
