/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  main_sidebar : [
    'intro',
    {
      type: 'category',
      label: '嵌入式开发',
      items: [
        {
          type: 'category',
          label: 'STM32',
          items: [
            'ESD/STM32_Encoder',
            'ESD/STMStudio'
          ]
        },
        {
          type: 'category',
          label: '硬件设计',
          items: ['ESD/Hardware_GasCtrl']
        }
      ]
    },
    {
      type: 'category',
      label: '机器人算法',
      items: [
        {
          type: "category",
          label: 'SLAM',
          items: [
            'Algorithm/SLAM_Move_Base_Source_Anys',
          ]
        },
        {
          type: 'category',
          label: '运动学算法',
          items: [
            'Algorithm/Steering_Wheel'
          ]
        }
      ]
    },
    {
      type: 'category',
      label: '树莓派开发',
      items: [
        'Raspi/Openwrt_Build',
        'Raspi/Ubuntu18'
      ]
    },
    {
      type: 'category',
      label: '成为帅气攻城狮',
      items: [
        'Development/Git_Config',
        'Development/Web_Maintenance_Guide',
        'Development/Clash_For_Linux',
        'Development/CLion_STM32_Development',
        'Development/Coding'
      ]
    },
    {
      type: 'category',
      label: '秘密基地',
      items: [
        'Base_Award_Exp'
      ]
    }
  ]
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
