/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  mySidebar: [
  	'intro',
    {
      type: 'category',
      label: '嵌入式开发 - STM32',
      items: ['STM32-Encoder'],
    },
    {
      type: 'category',
      label: '嵌入式开发 - 硬件',
      items: ['Hardware-GasCtrl'],
    },
  	{
  	  type: 'category',
  	  label: '树莓派开发 - Raspi',
  	  items: ['Raspi-Openwrt-Build','Raspi-Ubuntu'],
  	},
    {
  	  type: 'category',
  	  label: '机器人开发 - SLAM',
  	  items: ['Fill-empty'],
  	},
    {
      type: 'category',
      label: '成为帅气攻城狮',
      items: ['CLion-STM32-Development','coding','STMStudio'],
    },
    {
      type: 'category',
      label: '秘密基地',
      items: ['myLove'],
    },
  	],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
